#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chmod 777 /etc/default/haproxy
sudo echo "ENABLED=1" >> /etc/default/haproxy
sudo echo "
frontend front
    bind *:80
    mode http
    default_backend back
backend back
    balance roundrobin
    server 2922-web-01 34.138.181.227:80 check
    server 2922-web-02 18.208.245.134:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
