#!/usr/bin/env bash
# scrip that displays indefinitely and show other line when receiving a SIGTERM signal

while ((13))
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible"' SIGTERM
done