#!/usr/bin/env bash
# Numbers 1 to 100 in list format.
# "FizzBuzz" is a multiple of 3 and 5.
# "Fizz" is a multiple of 3.
# "Buzz"  is a multiple of 5.
# otherwise, displays the number.

for num in {1..100}
do
  if (( num % 3 == 0 && num % 5 == 0 ))
  then
    echo "FizzBuzz"
  elif (( num % 3 == 0 ))
  then
    echo "Fizz"
  elif (( num % 5 == 0 ))
  then
    echo "Buzz"
  else
    echo "$num"
  fi
done
