#!/usr/bin/env bash
# Loops that print 1 to 10 and displays:
#   "bad luck" in 4th iteration
#   "good luck" in 8th iteration
#   "Holberton School" for others iterations

count=0
while [ $count -lt 10 ]
do
  if [ $count -eq 3 ]
  then
    echo "bad luck"
  elif [ $count -eq 7 ]
  then
    echo "good luck"
  else
    echo "Holberton School"
  fi
  (( count++ ))
done
